### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by mcl1234** [duniter/cesium#121]
I added 

```css
html {
  -webkit-user-select: all;
  -moz-user-select: all;
  -ms-user-select: all;
  user-select: all;
}
```

to add selectable text fo users 
in `cesium/www/css/style.css`
it seems to work , then users can copy / paste users' public key
